# Generated by Django 4.1.3 on 2023-11-24 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('haritha', '0002_doctore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=50)),
                ('p_phone', models.CharField(max_length=12)),
                ('booking_on', models.DateField(auto_now_add=True)),
                ('booked_to', models.DateTimeField()),
                ('doc_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haritha.doctore')),
            ],
        ),
    ]
